packages:
    - name: app
      type: go
      srcs:
        - go.mod
        - go.sum
        - "**/*.go"
      env:
        - CGO_ENABLED=0
      deps:
        - components/common-go:lib
      config:
        packaging: app
    - name: docker
      type: docker
      deps:
        - :app
      argdeps:
        - imageRepoBase
      config:
        dockerfile: leeway.Dockerfile
        image:
          - ${imageRepoBase}/containerd-metrics:${version}
